### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by codenameakshay** [Hash-Studios/healthapp#2]
Add license, in the readme.

**Comment by swai-collins** [comment]
Please assign this to me

**Comment by raziqfarid** [comment]
@codenameakshay @LiquidatorCoder Interested about learning on license, can you assign this to me?

**Comment by codenameakshay** [comment]
> @codenameakshay @LiquidatorCoder Interested about learning on license, can you assign this to me?

The license is already present in the repo, you just need to add it in the readme, i.e. a header License, and then copy the whole license below it, at the end of the readme file.

**Comment by raziqfarid** [comment]
@codenameakshay @LiquidatorCoder @swai-collins  Completed
